[package]
name = "jason/wally"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
Hooks = "kampfkarren/roact-hooks@0.4.1"
RoactSpring = "chriscerie/roact-spring@1.0.1"
Rodux = "roblox/rodux@3.0.0"
RoduxHooks = "solarhorizon/rodux-hooks@0.3.0"
Promise = "evaera/promise@4.0.0"
Knit = "sleitnick/knit@1.4.7"
Sift = "csqrl/sift@0.0.3"
Cmdr = "evaera/cmdr@1.9.0"